[project]
name = "lab8-tg-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "aiogram>=3.19.0",
    "orjson>=3.10.16",
    "python-dotenv>=1.1.0",
    "uvloop>=0.21.0",
]

